name: Java Code Review

on:
  pull_request:
    branches: [ main ]

jobs:
  copilot-review:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup JDK
      uses: actions/setup-java@v2
      with:
        java-version: 11

    - name: Setup Maven
      uses: v1sion/setup-maven@v1
      with:
        maven-version: '3.8.1'

    - name: Install GitHub Copilot
      uses: Open-At-Source/copilot-action@v1.0.0
      with:
        language: java
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Review Java code
      run: |
        git fetch origin pull/${{ github.event.pull_request.number }}/head:${{ github.event.pull_request.head.ref }}
        git checkout ${{ github.event.pull_request.head.ref }}
        git config --global user.email "bot@example.com"
        git config --global user.name "GitHub Copilot"
        copilot review --ignore-patterns "**/target/**,**/build/**"
